#include "palette.h"

ALLEGRO_COLOR COLOR_BLACK;
ALLEGRO_COLOR COLOR_WHITE;
ALLEGRO_COLOR COLOR_GRAY;
ALLEGRO_COLOR COLOR_YELLOW;
ALLEGRO_COLOR COLOR_GREEN;

ALLEGRO_COLOR COLOR_ENEMY_BUTTON;
ALLEGRO_COLOR COLOR_DEFENDER_BUTTON;

ALLEGRO_COLOR COLOR_TRANSPARENT;

void init_colors()
{
    COLOR_BLACK = al_map_rgb(0, 0, 0);
    COLOR_WHITE = al_map_rgb(255, 255, 255);
    COLOR_GRAY = al_map_rgb(110, 112, 110);
    COLOR_YELLOW = al_map_rgb(255, 204, 0);
    COLOR_GREEN = al_map_rgb(50, 168, 82);

    COLOR_ENEMY_BUTTON = al_map_rgb(245, 66, 96);
    COLOR_DEFENDER_BUTTON = al_map_rgb(66, 135, 245);

    COLOR_TRANSPARENT = al_map_rgba(0, 0, 0, 0);
}
